name: CI

# Controla quando o fluxo de trabalho será executado (Gatilhos)
on:
  push:
    branches: [ "principal" ]
  
  pull_request:
    types: [opened, synchronize, reopened] # Mais robusto que apenas branches

  workflow_dispatch:

# Uma execução de fluxo de trabalho é composta de um ou mais trabalhos
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Faz check-out do seu repositório
      - uses: actions/checkout@v3

      # Executa um script de uma linha
      - name: Executa script de uma linha
        run: echo Fluxo de trabalho inicial executado com sucesso!

      # Executa um script multi-linha
      - name: Mensagem de Conclusão
        run: |
          echo Fluxo de trabalho testado e funcionando.
