nome: CI

# Controla quando o fluxo de trabalho será executado (Gatilhos)
on:
  push:
    branches: [ "principal" ]
  
  pull_request:
    branches: [ "principal" ]

  workflow_dispatch:

# Uma execução de fluxo de trabalho é composta de um ou mais trabalhos
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Etapa 1: Faz check-out do seu repositório para que o job possa acessar os arquivos
      - uses: actions/checkout@v3

      # Etapa 2: Executa um script de uma linha
      - name: Executa script de uma linha
        run: echo Fluxo de trabalho inicial executado com sucesso!

      # Etapa 3: Executa um script multi-linha
      - name: Mensagem de Conclusão (Próximos Passos)
        run: |
          echo Adicione aqui as ações para
          echo - Instalar Dependências
          echo - Compilar seu Código
          echo - Executar Testes Unitários
